#!/bin/bash

# This test file will be executed against after building a container with the
# 'basic' scenario in 'test/test/zscaler/scenarios.json'.
#
# For more information, see: https://github.com/devcontainers/cli/blob/main/docs/features/test.md
#
#
# This test (as well as any of the other scenarios in 'scenarios.json') can be run with the following command:
#
#    devcontainer features test \
#               --features color \
#               --skip-autogenerated \
#               /path/to/this/repo

set -e

# Optional: Import test library bundled with the devcontainer CLI
# Provides the 'check' and 'reportResults' commands.
source dev-container-features-test-lib

# Feature-specific tests
# The 'check' command comes from the dev-container-features-test-lib.
check "Zscaler file is present" bash -c "test -f /usr/local/share/ca-certificates/custom-ca/ZscalerRootCertificate-2048-SHA256.crt"
check "Able to download file" bash -c "wget https://www.google.com"

# Report result
# If any of the checks above exited with a non-zero exit code, the test will fail.
reportResults
